---
-  hosts: webserver
   become: yes

   tasks:
   - name: apache is installed
     yum:
       name: httpd
       state: present

   - name: apache is running
     service:
       name: httpd
       state: started
...
